### ISSUE TITLE
Local anisotropy plots

### ISSUE THREAD

**Issue by schienstockd** [phylars/ILEE_CSK#2]
Hello,

Thank you for your framework! Do you have an example code to reproduce the local anisotropy from your Figure 1?

Thanks!

Dominik

**Comment by phylars** [comment]
Hi Dominik,

Sorry for responding late. I believe I have a build-in function called "analyze_anisotropy_2d". Please check my raw code to find it. After you use this function to find anisotropy of each local box, you use the following code to draw:

---
anisotropy = analyze_anisotropy_2d (img_sk, radius = 90, box_size = 45, weighting_method = 'by_length', return_box_data = True)

box_isotropy = anisotropy[5]
center_coor = anisotropy[1]
eigvec_1 = anisotropy[3][:,:,:,0]

plt.figure(figsize = (18, 18))
#plt.imshow(img_binary, cmap = 'binary')
plt.scatter(points[:,0],points[:,1], s=0.26, color = 'black', alpha = 0.86)
center_list = center_coor.reshape(-1,2)
#.scatter(center_list[:,0], center_list[:,1], s=6, color = 'blue', alpha = 0.86)
plt.axis('off')
for i in range(1,53):
    for ii in range(1,53):
        hc,wc = center_coor[i,ii]
        he,we = eigvec_1[i,ii]*box_isotropy[i,ii]/454*90
        h0 = hc-he/2
        h1 = hc+he/2
        w0 = wc-we/2
        w1 = wc+we/2
        plt.plot([h0,h1], [w0,w1], color = 'red', linewidth = 2.6, alpha = 0.86)
---

Please tell me if you have any questions.


Pai Li

Research Associate, Ph.D.

Day Lab, MPS 4200

Department of Plant, Soil and Microbial Sciences

Michigan State University



________________________________
From: Dominik Schienstock ***@***.***>
Sent: Saturday, October 21, 2023 2:16 AM
To: phylars/ILEE_CSK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [phylars/ILEE_CSK] Local anisotropy plots (Issue #2)


Hello,

Thank you for your framework! Do you have an example code to reproduce the local anisotropy from your Figure 1?

Thanks!

Dominik

**Comment by schienstockd** [comment]
Cool - Thanks!
